[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]
viaIr = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./script/inputs" }]

evm_version = "prague"