[workspace]
members = [
    "libs",
    "setup/trusted-setup",
    "prove",
    "verify/verify-rust",
    "protocol-script"
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.7.0", package = "icicle-runtime" }
icicle-core = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.7.0", package = "icicle-core" }
icicle-hash = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.7.0", package = "icicle-hash" }
icicle-bls12-381 = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.7.0", package = "icicle-bls12-381"}
ark-bls12-381 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
libs = { path = "libs" }
prove = { path = "prove" }
verify = { path = "verify/verify-rust" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.4"
num-bigint = "0.4"
num-traits = "0.2"
rayon = "1.7"
rand = "0.8"
bincode = "1.3"